apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: sample
spec:
  rules:
    - host: sample.daleaws.co.uk
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: http