apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: kube-system
spec:
  encryptedData:
    foo: AgAYVUcvSYHsIBifvc40vr6pmUfo7F6OpvuCk/eyzpzJXhpwVs8TcZF6jV2NJRJjru7c2w7nUs8OmJbAa8E98BnDGC8++a8mjSD7jI6AVwMLCXT/Stn1QAcIpnGn82t/FUCKzXn/8bwIssNhtEx+UzZjUflVYLY6oN+7/yxZOvfsL4wOGtC7uOa6aQUgb8tAE+IUj3ZZXbBFpRL0dMNlCGkWuYLs89df7xoeTmuGaoolWCMcjhKEEA28iu+YCCPgTfCCq1tRq9v6Xy+KocNazOMjU3dQLCV+hUvOo9EiNXERWGk4D/QbnMK1GxkYoPKnlPoicok2ZbRwS0wYoTZvFlY2H52aMqE5ny/EHa5YgaE0+qJq5LvnHOV9G+uGxY3WhSbk6EptIrwhjQQ2b9E8gADQvPRTs4QtIAAyoBlmGQKmJgbId2+zSf9lRhFwlk+SRyuUT/YUCSKaBXoqNK2J40HtlizFdsmXUBSEJL8Vp54nS4jEcWeq0SCLci33so7vzlIyHhABSUYI7Icd+rANUKhv7Lw1IzRAcaLDy07hBZ8B9vLPlx4cm7OGVhweLDji/I8VqujWVIIr3Q2n4fCwKrlsKP4cSKZK9PJPzU05GIRvv0C0r+3EzJDXFAjqvvmzjgE/xbH3S1r7qD4EiqaYQn0CtSIijlxURqYaQdg1BwM4/QV7boPoCX1jSYBxgaYWQj4Es3M=

