apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: kube-system
spec:
  encryptedData:
    foo: AgAb4fn26yyat7SWbtk78QeM2DFJPb+nkY32O6RIN35tnT1Mua0AKI8+/xS/seLRoB4yDfWUN3bTYjh3krtoTDogWvQmnZaMr9LEYczAp8RJItwRdxQ/mghFhaJurnmN9YQa1ebrrRF1EviIvpR+RzphDAsBqcohf6N/6hBxoRIkPJXj8Lejhgw5PcIMeZ3VGjDLl8w5r/ivq7zhZThO9MzueP7iIYly5ZjLUKqGlhUdDgM848IEpv24nqZUjovr9e9Y22VWO6ojEaaPuBXjKIn5Gigq455xBlpqU79lFS8V/PiY8CTo03Du6RXYUcXN6/pSlJ9rv4Iv9eqeBspEs9A2tkXvQZ/Y+7cwXe2wiKfS+yIEFGTB/WN9QaN/hXgU4O20uaN+EMMKpselKJttV/eUeauCBTWIOw5m8fwaYsC48GjMRrwDye0bULX8EdzhXAKeCj1DlmMnTcfU4VB8/rAxt67wpAyCjSlel6li9Ys/MJJi62tWZtYxAILmqGHkfxRcPOnEJgH1D8JmgNAFi1zP7bWuELWvi7YRvP2a3iPhn59g25NxuCKk7Q1tOtggYOt5KhUindTFjHVrYfdKVmt8u60HHc3JFFYRit5D7WxMXq03ZpCZw2u6YjVWt/4cw0ZPKIUcRG+dEhoT3Eeub3hAbcwtcsTbUILg4eo0MnhykxPSiVQ3kNGjTT5SnjNO8N0IBrA=

